// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8yY-FubzRSeHtItSxjnJvomD9NIsH-FQ',
    appId: '1:600251379001:web:022444f1f576107deb4ce8',
    messagingSenderId: '600251379001',
    projectId: 'bucketlist-questly',
    authDomain: 'bucketlist-questly.firebaseapp.com',
    storageBucket: 'bucketlist-questly.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUVJwvSOA7lcq3GWT1MZgTTtwg-1QS6o0',
    appId: '1:600251379001:android:79ddecef17de85d9eb4ce8',
    messagingSenderId: '600251379001',
    projectId: 'bucketlist-questly',
    storageBucket: 'bucketlist-questly.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9bZI3ZskQh38xY7Bxe8G8GKoWrX0BVz0',
    appId: '1:600251379001:ios:799f9447b1e9854deb4ce8',
    messagingSenderId: '600251379001',
    projectId: 'bucketlist-questly',
    storageBucket: 'bucketlist-questly.firebasestorage.app',
    androidClientId: '600251379001-0ecbmdj85gk97sahcju1a06sf92c8vi3.apps.googleusercontent.com',
    iosClientId: '600251379001-ck1b7kuch0dg0uan7dsfgg7qiued4qk9.apps.googleusercontent.com',
    iosBundleId: 'com.questly.list',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9bZI3ZskQh38xY7Bxe8G8GKoWrX0BVz0',
    appId: '1:600251379001:ios:799f9447b1e9854deb4ce8',
    messagingSenderId: '600251379001',
    projectId: 'bucketlist-questly',
    storageBucket: 'bucketlist-questly.firebasestorage.app',
    androidClientId: '600251379001-0ecbmdj85gk97sahcju1a06sf92c8vi3.apps.googleusercontent.com',
    iosClientId: '600251379001-ck1b7kuch0dg0uan7dsfgg7qiued4qk9.apps.googleusercontent.com',
    iosBundleId: 'com.questly.list',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8yY-FubzRSeHtItSxjnJvomD9NIsH-FQ',
    appId: '1:600251379001:web:5f1714941be07427eb4ce8',
    messagingSenderId: '600251379001',
    projectId: 'bucketlist-questly',
    authDomain: 'bucketlist-questly.firebaseapp.com',
    storageBucket: 'bucketlist-questly.firebasestorage.app',
  );
}
